name: build docker image
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - '.github/workflows/docker-image.yml'
      - '.dockerignore'
      - '!**/LICENSE'
      - '!**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: doing checkout
      uses: actions/checkout@v4
    - name: build Raspbian PI Zero W image armv6
      run: docker buildx bake release
      env:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_REPOSITORY: ${{ github.repository }}
        TAG_SHA: ${{ github.sha }}
        DOCKER_TAG: latest

